version: '3.0'
services:
  mongo:
    image: mongo:4.2
    container_name: "mongo"
    volumes:
      - mongo_data:/data/db
    restart: always

  madi-the-koala:
    container_name: "madi"
    build: .
    depends_on:
      - mongo
    environment:
      - PRINCESS_TRIXIE_TOKEN=${PRINCESS_TRIXIE_TOKEN}
    restart: always

volumes:
  mongo_data: